### ISSUE TITLE
Remind users to set ACCOUNT_KEY as a secret

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/spektate#12]
Related to #6 

We should find a way to make this happen automatically too.

![](https://user-images.githubusercontent.com/3119513/63219439-d4864c80-c126-11e9-8473-c1b1c687929b.png)

**Comment by andrebriggs** [comment]
@samiyaakhtar I don't think this is an issue anymore which the variable group scripts we have

**Comment by samiyaakhtar** [comment]
@andrebriggs no longer an issue, closing
