### ISSUE TITLE
CLI version and release versions don't match up

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/spektate#13]
Latest  release:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/3119513/63219597-ca198200-c129-11e9-967c-eb1d4e1f60ff.png">

I get:
```
$ ./cli-macos --version
0.1.0
```

**Comment by andrebriggs** [comment]
@samiyaakhtar cli?

**Comment by samiyaakhtar** [comment]
Extremely out of date, from the times we had a cli in this repo. Closing
