### ISSUE TITLE
spektate doesn't show filtered results in ubuntu

### ISSUE THREAD

**Issue by edaena** [microsoft/spektate#36]
OS: ubuntu

**Repro:**
Run `spex deployments get -c <commit_id>`

**Expected:**
Filtered results

**Seen:**
All of the results

**Comment by samiyaakhtar** [comment]
@edaena Is this still a pending issue? If so, we should test it and open an issue in the milestone in bedrock

**Comment by andrebriggs** [comment]
Let's close unless we can repro @edaena @samiyaakhtar

**Comment by samiyaakhtar** [comment]
closing, this is stale
