### ISSUE TITLE
Add ability to run update_pipeline.py with a parameter that has value is none

### ISSUE THREAD

**Issue by TaiNguyen2406** [microsoft/spektate#69]
Hello @samiyaakhtar ,I am using Bedrock. I have 3 stages corresponding to 3 environments (dev, qa, prod), each of which is transformed by Fabrikate into Infra-materialized. I am using Spektate in 3 places.
1. After building the image.
2. After the release (release stage).
3. After Fabrikate transforms.
After running at positions 1 and 2, Spektate creates and updates a row but when running at position 3, it creates a new line. I expect that after running, there will be only 1 row for each environment.
I have found a solution to this problem, but it needs a little modification in the script. The script needs to support running with an input variable of 1 none value
 ex:
>  python "$ HOME / spektate / pipeline-scripts / update_pipeline.py" $ (ACCOUNT_NAME) $ (ACCOUNT_KEY) $ (TABLE_NAME) $ (PARTITION_KEY ) imageTag $ IMAGE_TAG p2 $ BUILD_TAG **manifestCommitId**
I have also tried to fork the code and changed it myself. Can you take a look?
https://github.com/TaiNguyen2406/spektate/blob/master/pipeline-scripts/update_pipeline.py

**Comment by samiyaakhtar** [comment]
Hi @TaiNguyen2406, apologies for the late response here. Thanks for the suggestion above - we have actually been expecting the use of [spk cli](https://github.com/CatalystCode/spk/blob/master/guides/service-introspection-onboarding.md#2-ci-pipeline-configuration) to be downloaded and ran for updating the pipelines and so we haven't managed to keep these python scripts up to date. 

Would you like to make a PR for this change if you prefer to use the python scripts from your pipelines?

**Comment by TaiNguyen2406** [comment]
Hi, I've created pull request.
